test-job1:
    stage: test
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"
        - echo "This job tests something."
        
test-job2:
    stage: test
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"
        - echo "This job tests some other thing."