/**
 * Notes on implementation
 * 
 * 1. each solution array holds all solutions for the given board
 */

solutionsConfig = {
    "board_3x21a": {
        solutionsArray: [
            "UUF.XNNNTTTZZWWIIIIIV UFFXXXYNNT.ZPPWWLLLLV UUFFXYYYYTZZPPPWL.VVV",
            "UUF.XNNNTTTZZWWIIIIIV UFFXXXYNNT.ZWWPPLLLLV UUFFXYYYYTZZWPPPL.VVV",
            "UUF.XNNNZZTTTWWIIIIIV UFFXXXYNNZ.TPPWWLLLLV UUFFXYYYYZZTPPPWL.VVV",
            "UUF.XNNNZZTTTWWIIIIIV UFFXXXYNNZ.TWWPPLLLLV UUFFXYYYYZZTWPPPL.VVV",
            "UUX.FNNNTTTZZWWIIIIIV UXXXFFYNNT.ZPPWWLLLLV UUXFFYYYYTZZPPPWL.VVV",
            "UUX.FNNNTTTZZWWIIIIIV UXXXFFYNNT.ZWWPPLLLLV UUXFFYYYYTZZWPPPL.VVV",
            "UUX.FNNNZZTTTWWIIIIIV UXXXFFYNNZ.TPPWWLLLLV UUXFFYYYYZZTPPPWL.VVV",
            "UUX.FNNNZZTTTWWIIIIIV UXXXFFYNNZ.TWWPPLLLLV UUXFFYYYYZZTWPPPL.VVV",
            "UUX.TPPPWZZFNNNIIIIIV UXXXTPPWWZ.FFYNNLLLLV UUXTTTWWZZFFYYYYL.VVV",
            "UUX.TWPPPZZFNNNIIIIIV UXXXTWWPPZ.FFYNNLLLLV UUXTTTWWZZFFYYYYL.VVV",
            "UUX.TYYYYFFZZWWIIIIIV UXXXTNNYFF.ZPPWWLLLLV UUXTTTNNNFZZPPPWL.VVV",
            "UUX.TYYYYFFZZWWIIIIIV UXXXTNNYFF.ZWWPPLLLLV UUXTTTNNNFZZWPPPL.VVV",
            "UUX.ZZNNNFTTTWWIIIIIV UXXXZNNYFF.TPPWWLLLLV UUXZZYYYYFFTPPPWL.VVV",
            "UUX.ZZNNNFTTTWWIIIIIV UXXXZNNYFF.TWWPPLLLLV UUXZZYYYYFFTWPPPL.VVV",
            "UUX.ZZWWTTTFNNNIIIIIV UXXXZPPWWT.FFYNNLLLLV UUXZZPPPWTFFYYYYL.VVV",
            "UUX.ZZWWTTTFNNNIIIIIV UXXXZWWPPT.FFYNNLLLLV UUXZZWPPPTFFYYYYL.VVV"
        ],
        active: true
    },
    "board_3x21b": {
        solutionsArray: [
            "UUUWLLLL.FTTTXIIIIIZV UYUWWNNLFF.TXXXPPZZZV YYYYWWNNNFFT.XPPPZVVV",
            "UUUWLLLL.FTTTXPPPZVVV UYUWWNNLFF.TXXXPPZZZV YYYYWWNNNFFT.XIIIIIZV",
            "UUXIIIII.NNFTTTWWZVVV UXXXPPLNNN.FFTWWYZZZV UUXPPPLLLLFF.TWYYYYZV]"
        ],
        active: false
    },
    "board_3x21c": {
        solutionsArray: [],
        active: false
    },
    "board_3x21d": {
        solutionsArray: [],
        active: false
    },
    "board_6x10": {
        solutionsArray: [],
        active: false
    },
    "board_8x8a": {
        solutionsArray: [],
        active: false
    },
    "board_4x15": {
        solutionsArray: [],
        active: false
    }    
};